version: "3"
networks:
  gitea:
    external: false 
volumes:
   gitea:
     name: gitea
   mysql:
     name: mysql    
services:
  server:
    image: nikhilgoenka/gitea
    container_name: gitea
    environment:
      - USER_UID=998
      - USER_GID=100
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2234:24"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - mysql:/var/lib/mysql
  http-server:
    image: nikhilgoenka/http_server 
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - API_URL=${API_URL}
      - COMPILATION_ERROR_WORKFLOW=${COMPILATION_ERROR_WORKFLOW}
      - COMPILATION_ERROR_EASYTRADE_WORKFLOW=${COMPILATION_ERROR_EASYTRADE_WORKFLOW}
      - EASYTRADE_WORKFLOW=${EASYTRADE_WORKFLOW}
      - FLASK_ENV="development"
    networks:
      - gitea
    ports:
      - "5000:5000"
